[application]

[web.app]

# HTML title tag content
title = "maze_rs"

# Additional CSS style files
style = []

[bundle]
identifier = "Maze Rs"
description = "Desktop app for visualizing maze solving algorithms"
publisher = "Oscar Aspelin"
icon = ["assets/icon/32x32.png", "assets/icon/16x16.png"]
